service: shrink

frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  devDynamoCapacity:
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1
  prodDynamoCapacity:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  environment:
    SLS_STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:table/${self:custom.stage}-shrink-urls"
      Effect: Allow

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get

resources:
  Resources:
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.${self:custom.stage}DynamoCapacity}
        TableName: "${self:custom.stage}-shrink-urls"
